marasem/urls.py
from django.urls import path

from marasem.views import CreateNewEvent, EditEvent, load_cities, DeleteEvent

urlpatterns = [
    path('newevent/<yadId>', CreateNewEvent, name="newevent"),
    path('editevent/<yadId>/<eventId>', EditEvent, name="editevent"),
    path('deleteevent/<yadId>/<eventId>', DeleteEvent, name="deleteevent"),
    path('ajax/load-cities/', load_cities, name='ajax_load_cities'),  # AJAX

]

yad/urls.py
from django.urls import path
from yad.views import YadbodList, Yad_detail, add_salavat, add_100_salavat, Yad_detail_2, add_fatehe, reyad, CreateYad, \
    load_cities2, \
    EditYad, DeleteYad, yad_for_state, yad_for_city, SearchYadView, Yad_Total_Random, Yad_Total_Salavat, \
    Yad_Total_Fatehe, Yad_Total_Quran, Help, Send_eitaa, Reseteitaa, Delete2, Create_eitaa, Salsms, fix_broken_images

# path('yadbod' ,YadbodList.as_view()),




urlpatterns = [
    path('' ,YadbodList.as_view(),name="yadbodl"),
    path('help', Help, name="help"),
    path('sendeitaa', Send_eitaa, name="Sendeitaa"),
    path('createitaa/<yadId>', Create_eitaa, name="createitaa"),
    path('reseteitaa', Reseteitaa, name="reseteitaa"),
    path('salsms', Salsms, name="salsms"),
    path('delete2', Delete2, name="delete2"),
    path('yadbood/<yadId>', Yad_detail_2, name="yadboodd"),
    path('yadbood/state/<stateId>/<page>', yad_for_state, name="yad_for_state"),
    path('yadbood/city/<cityId>/<page>', yad_for_city, name="yad_for_city"),
    
    path('yadbood/total_random/<page>', Yad_Total_Random, name="total_random"),
    path('yadbood/total_salavat/<page>', Yad_Total_Salavat, name="total_salavat"),
    path('yadbood/total_fatehe/<page>', Yad_Total_Fatehe, name="total_fatehe"),
    path('yadbood/total_quran/<page>', Yad_Total_Quran, name="total_quran"),

    path('search', SearchYadView.as_view()),




    #json
    path('yadbod/<yadId>', Yad_detail, name="yadbodd"),

    path('yadbod/<yadId>/salavat', add_salavat, name="salavat"),
    path('yadbod/<yadId>/100salavat', add_100_salavat, name="100salavat"),

    path('yadbod/<yadId>/fatehe', add_fatehe, name="fatehe"),
    path('yadbod/<yadId>/reyad', reyad, name="reyad"),


    path('create', CreateYad, name="create"),
    path('edit/<yadId>', EditYad, name="edit"),
    path('delete/<yadId>', DeleteYad, name="delete"),

    path('fix-images/', fix_broken_images, name='fix_broken_images'),

    # Ajax
    path('ajax/load-cities2/', load_cities2, name='ajax_load_cities2'),  # AJAX

]

marasem/models.py
from django.db import models

# Create your models here.
from mycity.models import State, City
from yad.models import Yad


class Marasem(models.Model):
    title = models.CharField(max_length=150, verbose_name='عنوان مراسم')
    address=models.TextField(verbose_name='آدرس', null=True, blank=True)
    event_date = models.DateField(verbose_name='تاریخ مراسم' , null=True, blank=True)
    starttime=models.TimeField(verbose_name='ساعت شروع مراسم' , null=True, blank=True)
    finishtime=models.TimeField(verbose_name='ساعت پایان مراسم' , null=True, blank=True)
    yad=models.ForeignKey(Yad,blank=True, null=True, on_delete=models.CASCADE ,verbose_name='یادبود')
    active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')
    state = models.ForeignKey(State, on_delete=models.SET_NULL,related_name='state', blank=True, null=True, verbose_name='استان')
    city = models.ForeignKey(City, on_delete=models.SET_NULL,related_name='city', blank=True, null=True, verbose_name='شهر')

marasem/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404, JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from jalali_date import datetime2jalali

from custom_login.models import MyUser
from marasem.form import CreateMarasemForm
from marasem.models import Marasem
from mycity.models import City
from yad.models import Yad


@login_required(login_url='/register')
def CreateNewEvent(request,*args,**kwargs):
    user_id = request.user.id
    user = MyUser.objects.get(id=user_id)
    if user is None:
        raise Http404('کاربر مورد نظر یافت نشد')
    yadId=kwargs['yadId']
    yadbood=Yad.objects.filter(id=yadId).first()
    owner = yadbood.owner



    create_form = CreateMarasemForm(request.POST or None
                                # initial={'first_name': user.first_name, 'last_name': user.last_name}
                                )

    context = {'create_form': create_form,
               'yad':yadbood,
               'title':"ایجاد مراسم"

               }

    if user!=owner and user.mobile != '09151006447':
        raise Http404('شما این دسترسی را ندارید')

    if user==owner:
        if create_form.is_valid():
            title = create_form.cleaned_data.get('title')
            address = create_form.cleaned_data.get('address')
            event_date= create_form.cleaned_data.get('event_date')
            finishtime= create_form.cleaned_data.get('finishtime')
            starttime= create_form.cleaned_data.get('starttime')
            state= create_form.cleaned_data.get('state')
            city= create_form.cleaned_data.get('city')


            Marasem.objects.create(
                title=title,
                state=state,
                city=city,
                address=address,
                event_date= event_date,
                finishtime=finishtime,
                starttime=starttime,
                yad=yadbood
            )
            return redirect(f"/yadbood/{yadId}")
    return render(request, 'event/create_event.html', context)


@login_required(login_url='/register')
def EditEvent(request,*args,**kwargs):
    user_id = request.user.id
    user = MyUser.objects.get(id=user_id)
    if user is None:
        raise Http404('کاربر مورد نظر یافت نشد')
    yadId=kwargs['yadId']
    yadbood=Yad.objects.filter(id=yadId).first()
    owner = yadbood.owner
    eventID=kwargs['eventId']
    event_for_edit=Marasem.objects.filter(id=eventID).first()


    edit_event_form = CreateMarasemForm(request.POST or None,
                                initial={'title': event_for_edit.title,
                                         'state': event_for_edit.state,
                                         'city': event_for_edit.city,
                                         'address': event_for_edit.address,
                                         'event_date':event_for_edit.event_date,
                                         'starttime':event_for_edit.starttime,
                                         'finishtime':event_for_edit.finishtime,



                                         }
                                )
    context = {
        'edit_event_form': edit_event_form,
        'yad': yadbood,
        'title':"ویرایش مراسم"

    }

    if user==owner or user.mobile == '09151006447':
        if edit_event_form.is_valid():
            title = edit_event_form.cleaned_data.get('title')
            state = edit_event_form.cleaned_data.get('state')
            city = edit_event_form.cleaned_data.get('city')
            address = edit_event_form.cleaned_data.get('address')
            event_date= edit_event_form.cleaned_data.get('event_date')
            finishtime= edit_event_form.cleaned_data.get('finishtime')
            starttime= edit_event_form.cleaned_data.get('starttime')

            event_for_edit.title=title
            event_for_edit.state=state
            event_for_edit.city=city
            event_for_edit.address=address
            event_for_edit.event_date= event_date
            event_for_edit.finishtime=finishtime
            event_for_edit.starttime=starttime
            event_for_edit.save()
            return redirect(f"/yadbood/{yadId}")
    return render(request, 'event/edit_event.html', context)

@login_required(login_url='/register')
def DeleteEvent(request,*args,**kwargs):
    user_id = request.user.id
    user = MyUser.objects.get(id=user_id)
    if user is None:
        raise Http404('کاربر مورد نظر یافت نشد')
    yadId=kwargs['yadId']
    yadbood=Yad.objects.filter(id=yadId).first()
    owner = yadbood.owner
    eventID=kwargs['eventId']
    event_for_delete=Marasem.objects.filter(id=eventID).first()



    if user==owner or user.mobile == '09151006447':
        if event_for_delete is not None:
            event_for_delete.delete()
            return redirect(f"/yadbood/{yadId}")

# AJAX
def load_cities(request):
    state_id = request.GET.get('state_id')
    cities = City.objects.filter(state_id=state_id).all()
    return render(request, 'event/city_dropdown_list_options.html', {'cities': cities})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)

marasem/templates/event/city_dropdown_list_options.html
<option value="">انتخاب شهر</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

marasem/templates/event/create_event.html
{% extends 'shared/_MainLayout.html' %}

{% load jalali_tags %}
{% load static %}

{% block content %}


<div id="appCapsule">
        <div class="login-form">
            <div class="section">
                <h3> ایجاد مراسم </h3>
                <h4>{{ yad.title }} {{ yad.name }} {{ yad.family }}</h4>
            </div>
            <div class="container col-10 justify-content-center">



                <form method="post" action="#" enctype=multipart/form-data
                      id="eventForm" data-cities-url="{% url 'ajax_load_cities' %}">
                    {% csrf_token %}
                    <div class="form-group boxed">
                        <div class="input-wrapper">
                            {{ create_form.title }}
                          </div>
                    </div>


                    <div class="form-group boxed">
                        <div class="input-wrapper">
                            {{ create_form.family }}
                        </div>
                    </div>


                    <div class="form-group boxed">
                        <div class="input-wrapper">
                            <label class="label">استان</label>
                            {{ create_form.state }}
                        </div>
                    </div>


                    <div class="form-group boxed">
                        <div class="input-wrapper">
                            {{ create_form.city }}
                        </div>
                    </div>


                    <div class="form-group boxed">
                        <div class="input-wrapper">
                            {{ create_form.address }}
                        </div>
                    </div>




                    <div class="form-group boxed">
                        <div class="input-wrapper">
                            تاریخ مراسم:
                            {{ create_form.event_date }}
                        </div>
                    </div>


                   <div class="form-group boxed">
                        <div class="input-wrapper">
                                                        <label class="label">ساعت شروع:</label>


                            {{ create_form.starttime }}
                        </div>
                    </div>


                    <div class="form-group boxed">
                        <div class="input-wrapper">
                                                        <label class="label">ساعت پایان:</label>
                            {{ create_form.finishtime }}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block btn-lg">ثبت</button>

                </form>
            </div>
        </div>
    </div>

<link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
<script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_state").change(function () {
        const url = $("#eventForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const stateId = $(this).val();  // get the selected state ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'state_id': stateId       // add the state id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });
</script>
<script>
$('.time-picker').timepicker({
            showMeridian: false
        });

</script>

{% endblock %}

marasem/templates/event/edit_event.html
{% extends 'shared/_MainLayout.html' %}

{% load jalali_tags %}
{% load static %}

{% block content %}


<div id="appCapsule">
        <div class="login-form">
            <div class="section">
                <h3> ویرایش مراسم </h3>
                <h4>{{ yad.title }} {{ yad.name }} {{ yad.family }}</h4>
            </div>
            <div class="container col-10 justify-content-center">



                <form method="post" action="#" enctype=multipart/form-data
                      id="eventForm" data-cities-url="{% url 'ajax_load_cities' %}">
                    {% csrf_token %}
                    <div class="form-group boxed">
                        <div class="input-wrapper">
                            {{ edit_event_form.title }}
                          </div>
                    </div>


                    <div class="form-group boxed">
                        <div class="input-wrapper">
                            {{ edit_event_form.family }}
                        </div>
                    </div>


                    <div class="form-group boxed">
                        <div class="input-wrapper">
                            <label class="label">استان</label>
                            {{ edit_event_form.state }}
                        </div>
                    </div>


                    <div class="form-group boxed">
                        <div class="input-wrapper">
                            {{ edit_event_form.city }}
                        </div>
                    </div>


                    <div class="form-group boxed">
                        <div class="input-wrapper">
                            {{ edit_event_form.address }}
                        </div>
                    </div>




                    <div class="form-group boxed">
                        <div class="input-wrapper">
                            تاریخ مراسم:
                            {{ edit_event_form.event_date }}
                        </div>
                    </div>


                   <div class="form-group boxed">
                        <div class="input-wrapper">
                                                        <label class="label">ساعت شروع:</label>


                            {{ edit_event_form.starttime }}
                        </div>
                    </div>


                    <div class="form-group boxed">
                        <div class="input-wrapper">
                                                        <label class="label">ساعت پایان:</label>
                            {{ edit_event_form.finishtime }}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block btn-lg">ثبت</button>

                </form>
            </div>
        </div>
    </div>

<link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
<script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_state").change(function () {
        const url = $("#eventForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const stateId = $(this).val();  // get the selected state ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'state_id': stateId       // add the state id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });
</script>
<script>
$('.time-picker').timepicker({
            showMeridian: false
        });

</script>

{% endblock %}

marasem/templates/event/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>